# Setup
title:        Maitek AI
tagline:      Thoughts on Machine Learning and Artificial Intelligence
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mathias Sundholm
  url:        https://www.linkedin.com/in/sundholm

# Gems
gems:
  - jekyll-paginate

#Others
kramdown:
  input: GFM
  syntax_highlighter: rouge

#highlighter: rouge
